version: '3'
services:

    eureka-server:
        image: eureka-server
        restart: on-failure
        container_name: eureka-server
        build:
            context: ./eureka-server
            dockerfile: Dockerfile
        ports:
            - 8761:8761
        networks: 
            - xml
        environment: 
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

    zuul-gateway:
        image: zuul-gateway
        restart: on-failure
        container_name: zuul-gateway
        build:
            context: ./zuul-gateway
            dockerfile: Dockerfile
        ports:
            - 8762:8762
        networks: 
            - xml
        environment: 
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
        depends_on: 
            - eureka-server

    authentication-service:
        image: authentication-service
        restart: on-failure
        container_name: authentication-service
        build:
            context: ./authentication-service
            dockerfile: Dockerfile
        ports:
            - 9100:9100
        networks:
            - xml
        environment: 
            DATABASE_USERNAME: root
            DATABASE_PASSWORD: root
            DATABASE_DOMAIN: mysql
            DATABASE_SCHEMA: xml
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
        depends_on: 
            - mysql
            - eureka-server

    mysql:
        image: mysql:8.0.19
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: mysql
        ports: 
            - 3306
        expose:
            - 3306
        networks: 
            - xml
        environment: 
            MYSQL_ROOT_PASSWORD: root
            # MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: xml
        volumes: 
            # - ./init:/docker-entrypoint-initdb.d/:ro
            - ./data.sql:/docker-entrypoint-initdb.d/data.sql

    friends-service:
        image: friends-service
        restart: on-failure
        container_name: friends-service
        build:
            context: ./friends-service
            dockerfile: Dockerfile
        ports: 
            - 8800:8800
        networks: 
            - xml
        environment: 
            DATABASE_USERNAME: root
            DATABASE_PASSWORD: root
            DATABASE_DOMAIN: mysql
            DATABASE_SCHEMA: xml
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
        depends_on: 
            - mysql
            - eureka-server

    profile-service:
        image: profile-service
        restart: on-failure
        container_name: profile-service
        build:
            context: ./profile-service
            dockerfile: Dockerfile
        ports:
            - 8900:8900
        networks: 
            - xml
        environment: 
            DATABASE_USERNAME: root
            DATABASE_PASSWORD: root
            DATABASE_DOMAIN: mysql
            DATABASE_SCHEMA: xml
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
        depends_on: 
            - mysql
            - eureka-server

    post-service:
        image: post-service
        restart: on-failure
        container_name: post-service
        build:
            context: ./post-service
            dockerfile: Dockerfile
        ports: 
            - 9000:9000
        networks: 
            - xml
        environment: 
            DATABASE_USERNAME: root
            DATABASE_PASSWORD: root
            DATABASE_DOMAIN: mysql
            DATABASE_SCHEMA: xml
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
        depends_on: 
            - mysql
            - eureka-server

    story-service:
        image: story-service
        restart: on-failure
        container_name: story-service
        build:
            context: ./story-service
            dockerfile: Dockerfile
        ports: 
            - 8500:8500
        networks: 
            - xml
        environment: 
            DATABASE_USERNAME: root
            DATABASE_PASSWORD: root
            DATABASE_DOMAIN: mysql
            DATABASE_SCHEMA: xml
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
        depends_on: 
            - mysql
            - eureka-server

    media-service:
        image: media-service
        restart: on-failure
        container_name: media-service
        build:
            context: ./media-service
            dockerfile: Dockerfile
        ports: 
            - 8400:8400
        networks: 
            - xml
        environment: 
            DATABASE_USERNAME: root
            DATABASE_PASSWORD: root
            DATABASE_DOMAIN: mysql
            DATABASE_SCHEMA: xml
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
        depends_on: 
            - mysql
            - eureka-server

networks: 
    xml:
        # driver: bridge
