version: '3'
services:

    authentication-service:
        image: authentication-service
        restart: on-failure
        container_name: authentication-service
        build:
            context: ./authentication-service
            dockerfile: Dockerfile
        ports: 
            - 9100:9100
        networks: 
            - xml
        environment: 
            DATABASE_USERNAME: root
            DATABASE_PASSWORD: root
            DATABASE_DOMAIN: mysql
            DATABASE_SCHEMA: xml
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
        depends_on: 
            - mysql
            - eureka-server

    post-service:
        image: post-service
        restart: on-failure
        container_name: post-service
        build:
            context: ./post-service
            dockerfile: Dockerfile
        ports:
            - 8700:8700
        networks: 
            - xml
        environment: 
            DATABASE_USERNAME: root
            DATABASE_PASSWORD: root
            DATABASE_DOMAIN: mysql
            DATABASE_SCHEMA: xml
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
        depends_on: 
            - mysql
            - eureka-server
        
    friends-service:
            image: friends-service
            restart: on-failure
            container_name: friends-service
            build:
                context: ./friends-service
                dockerfile: Dockerfile
            ports: 
                - 8800:8800
            networks:
                - xml
            environment:
                DATABASE_USERNAME: root
                DATABASE_PASSWORD: root
                DATABASE_DOMAIN: mysql
                DATABASE_SCHEMA: xml
                EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
            depends_on: 
                - mysql
                - eureka-server

    profile-service:
            image: profile-service
            restart: on-failure
            container_name: profile-service
            build:
                context: ./profile-service
                dockerfile: Dockerfile
            ports: 
                - 8900:8900
            networks: 
                - xml
            environment: 
                DATABASE_USERNAME: root
                DATABASE_PASSWORD: root
                DATABASE_DOMAIN: mysql
                DATABASE_SCHEMA: xml
                EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
            depends_on: 
                - mysql
                - eureka-server

    mysql:
            image: mysql:8.0.19
            restart: always
            container_name: mysql
            ports:
                - 3306
            networks: 
                - xml
            environment: 
                MYSQL_ROOT_PASSWORD: root
                MYSQL_USER: root
                MYSQL_PASSWORD: root
                MYSQL_DATABASE: xml
            volumes:
                - mysql-data:/var/lib/mysql

    eureka-server:
            image: eureka-server
            restart: on-failure
            container_name: eureka-server
            build: 
                context: ./eureka-server
                dockerfile: Dockerfile
            ports: 
                - 8761:8761
            networks: 
                - xml
            environment: 
                EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
        
    zuul-gateway:
        image: zuul-gateway
        restart: on-failure
        container_name: zuul-gateway
        build: 
            context: ./zuul-gateway
            dockerfile: Dockerfile
        ports: 
            - 8762:8762
        networks: 
            - xml
        environment: 
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
        depends_on: 
            - eureka-server

    agent-backend:
        image: agent-backend
        restart: on-failure
        container_name: agent-backend
        build:
            context: ./agent-backend
            dockerfile: Dockerfile
        ports:
            - 8600:8600
        networks: 
            - xml
        environment:
            DATABASE_USERNAME: root
            DATABASE_PASSWORD: root
            DATABASE_DOMAIN: mysql
            DATABASE_SCHEMA: xml
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
        depends_on: 
            - mysql
            - eureka-server

volumes:
    mysql-data: {}

networks: 
    xml:
        driver: bridge